### ISSUE TITLE
Bundling Failed

### ISSUE THREAD

**Issue by dip77** [twilio/TwilioChatJsReactNative#10]
Unable to resolve module `events` from `/Twilio2/node_modules/twilio-chat/browser/client.js`: Module does not exist in the module map

**Comment by aleksandrsivanovs** [comment]
Hi!

We don't include `events` in twilio-chat.js npm package, since it's not really required and should be handled by platform. React Native requires the developer apps to include `events` in package.json.

In the given example we do this: https://github.com/twilio/TwilioChatJsReactNative/blob/master/package.json#L14
