### ISSUE TITLE
Can't fetch Chat Client configuration

### ISSUE THREAD

**Issue by Parthasarath** [twilio/TwilioChatJsReactNative#23]
Hi @aleksandrsivanovs 
After successfully login the app i got error message below,
can't fetch Chat Client configuration, {"line": 21762, "column": 31, "sourceURL": "http://localhost:8081/index.io.bundle?platform=ios&dev=true&minify=false"}

I think it happen chat-client-configuration file invalid path,where can i placed chat-client-configuration.json and what are details i want fill that json file? Could you give me some solution to fix that one?

**Comment by aleksandrsivanovs** [comment]
we have exchanged emails since this issue was open.
just in case, will re-iterate here what has been said:
1) please refer to [README.md](https://github.com/twilio/TwilioChatJsReactNative/blob/master/README.md) you will need to start local ngrok server to serve configuration to the sample app (described in [Running the app](https://github.com/twilio/TwilioChatJsReactNative/blob/master/README.md#running-the-app) section)
2) the file `configuration.json` location and contents is described in the same (https://github.com/twilio/TwilioChatJsReactNative/blob/master/README.md) in [Token provider and Chat configuration](https://github.com/twilio/TwilioChatJsReactNative/blob/master/README.md#token-provider-and-chat-configuration) section
