### ISSUE TITLE
Token Authorization Failed

### ISSUE THREAD

**Issue by digitaldavenyc** [twilio/TwilioChatJsReactNative#6]
We've just gotten setup with React Native for Twilio Chat and are getting intermittent authentication failures. Our API (we are using the python-sdk) seems to be returning a correct token. I will include our Python & JavaScript code for generating and using a token.

React Native - actions.js

```
import { Client } from "twilio-chat";
import { AccessManager} from "twilio-common";
import { User } from '../models/user';
import * as events from '../constants/chat';

export const initialize = () => {
	let user = new User();

	return dispatch => {
		user.load((model) => {
			model.chatJWT((token) => {
				Client.create(token, {}).then((_client) => {
					let _manager = new AccessManager(token);
					_manager.on('tokenUpdated', am => {
						_client.updateToken(am.token)
					});
					_manager.on('tokenExpired', () => {
						model.chat(token).then(newToken => {
							_manager.updateToken(newToken);
						});
					})

					dispatch({
						type: events.CHAT_CONNECTION_SUCCESS,
						data: {
							client: _client,
							manager: _manager
						}
					})
				})
			})
		})
	}

}
```

It's really unfortunately that `Client.create` is not able to fail gracefully and return an error rather then causing an exception. I also dug around in the twilio-chat source code and could not find a way to verify a token before establishing a client connection.

Python API - auth.py

```
import json
from tornado_json.exceptions import APIError
from twilio.rest import Client
from twilio.jwt.access_token import AccessToken
from twilio.jwt.access_token.grants import ChatGrant

   def post(self):
        body = self.request.body.decode('utf-8')

        if not body:
            raise APIError(400, log_message="Please include a device ID to obtain a chat access token.")

        body = json.loads(body)
        device_id = body.get('device_id')
        account_sid = settings.TWILIO_SID
        client = Client(settings.TWILIO_SID, settings.TWILIO_AUTH_TOKEN)
        key = client.new_keys.create()
        service_sid = settings.TWILIO_CHAT_SERVICE_SID
        endpoint_id = f"APP:{self.user_id}:{device_id}"
        token = AccessToken(account_sid, key.sid, key.secret, identity=self.user_id)
        chat_grant = ChatGrant(endpoint_id=endpoint_id, service_sid=service_sid)
        token.add_grant(chat_grant)

        jwt = token.to_jwt()

        if jwt:
            self.response(jwt.decode('utf-8'))
```

Error Thrown by Twilio in React Native

```
console.error: "EMS E:", {}

console.error
    YellowBox.js:62:10
Object.error
    logger.js:51:18
<unknown>
    client.js:196:53
tryCallOne
    core.js:37:11
<unknown>
    core.js:123:14
<unknown>
    JSTimers.js:117:44
Object.callTimer
    JSTimersExecution.js:95:8
Object.callImmediatesPass
    JSTimersExecution.js:199:26
Object.callImmediates
    JSTimersExecution.js:214:29
<unknown>
    MessageQueue.js:228:41
MessageQueue.__guard
    MessageQueue.js:218:6
MessageQueue.__callImmediates
    MessageQueue.js:228:9
<unknown>
    MessageQueue.js:102:11
MessageQueue.__guard
    MessageQueue.js:218:6
MessageQueue.callFunctionReturnFlushedQueue
    MessageQueue.js:100:9
```

**Comment by aleksandrsivanovs** [comment]
Hi!

You are right, we don't have any method to parse the token and verify it before we try to authenticate with it.
Also, you are right once again, our `create` method is far from perfect - we are aware of it and have a plan to fix it (i.e. refactor the creation and finally remove deprecated public constructor of Chat client and etc.). Unfortunately, I can't give ETA on this work.

Can you, please, enable debug logging in the client and post the bigger log here? To enable debug logging provide the options to the`Client.create()`: http://media.twiliocdn.com/sdk/js/chat/releases/1.2.1/docs/Client.html#ClientOptions
Or, better, send the bigger log with description of the problem and link to this discussion to support@twilio.com - our Twilio support, since the log might contain some sensitive information.

I see that your mentioned token is correct (purely from JWT format and grant structure perspective).
we can possibly decline the token based on four reasons:
1) token expired (to check this case - please try to create token with longer expiry time and try with it)
2) token is malformed (this is not the case here, at first glance everything is correct with your token format-wise)
3) data in token is not correct (i.e., for example, you are providing chat service SID which doesn't exist for this account - please check your data through https://www.twilio.com/console/chat/services) 
4) unexpected error on backend.


Aleksandrs


P.S. In general - it's a good idea not to post your tokens openly in internet - the tokens contain some sensitive information about your account, like, SID. In case of authorization failures - feel free to contact our Twilio support via support@twilio.com email :)

**Comment by digitaldavenyc** [comment]
Thanks for the very in-depth update. I think we were doing some strange things in the backend regarding auth that could have contributed to the problem, but honestly not exactly sure what fixed it.

**Comment by aleksandrsivanovs** [comment]
awesome :)
you are welcome :)

**Comment by digitaldavenyc** [comment]
It's baaaaaaack .... we are getting this error again. I have no clue what could be causing this, it's so bizarre. It would be REALLY helpful if there was an auth validation endpoint somewhere we could at least call before sending the request that causes the app to crash and tell us what is wrong with our token.

**Comment by aleksandrsivanovs** [comment]
can you, please, refer to our support via support@twilio.com with the token you were using and which resulted in error? we can debug with exact token provided.

**Comment by digitaldavenyc** [comment]
I spoke with support and it was actually with the Python code that generates the JWT server side, it was the `endpoint_id `. The docs for created an auth token include `endpoint_id` but that is a deprecated field apparently, which is very confusing.

I still standby my other statement though, having a way to verify a token would incredibly helpful so the app does not crash on an invalid token.

**Comment by aleksandrsivanovs** [comment]
we don't provide token verification tool for now, as this is developer's personal information. 
can I close this issue for now?
